# Generated by Django 4.2.7 on 2026-01-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('service', models.CharField(max_length=50)),
                ('log_level', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
