# Generated by Django 5.2.10 on 2026-01-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='anomaly',
            constraint=models.UniqueConstraint(fields=('service', 'anomaly_type'), name='unique_service_anomaly'),
        ),
    ]
