# Generated by Django 4.2.7 on 2026-01-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('service', models.CharField(max_length=50)),
                ('log_level', models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['timestamp'], name='logs_logent_timesta_1e81d2_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['service'], name='logs_logent_service_aaf221_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['log_level'], name='logs_logent_log_lev_9da2d3_idx'),
        ),
    ]
