# Generated by Django 4.2 on 2026-02-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_logentry_timestamp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='anomaly',
            name='unique_service_anomaly',
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
